#!/bin/sh

# Generate SSL key, putting private key and self-signed certificate in same file, THEN
# generate a SSL key to be added to browsers:
if [[ ! -f /etc/squid/cert/internal.pem || ! -f /etc/squid/cert/external.der ]]; then
	mkdir -p /etc/squid/cert/
	cd /etc/squid/cert/
	openssl req -new -newkey rsa:4096 -sha256 -days 3650 -nodes -x509 -keyout internal.pem -out internal.pem -batch
	openssl x509 -in internal.pem -outform DER -out external.der
fi

# Remove possible pid
rm /var/run/squid.pid 2>/dev/null

# Create cache directories
echo "Initializing Squid cache..."
squid -Nz -f /opt/squid/squid.conf

# Start squid in the background
exec squid -YFCN -f /opt/squid/squid.conf
